### ISSUE TITLE
Ability to move bosses around in sidebar

### ISSUE THREAD

**Issue by Gollum69** [rugg0064/boss-health-indicators#1]
Currently there is no way to move the bosses around and thus it makes it quite messy when you for example add a quest boss, then raid bosses but forget another quest boss and then you go looking where that boss is. Obviously when you add alot of bosses it can stack up quite a lot. 

A suggestion I could think of is to either let us move individual bosses around, or perhaps a label/folder group so you can ToA bosses into ToA label, Quest bosses into Quest label etc to organise it much better, but perhaps that's another suggestion entirely. Or another way to minimize clutter could be an arrow to fold/unfold any info listed on it, so it doesn't constantly display the percentages you have listed.

**Comment by rugg0064** [comment]
Thanks for bringing that up. Do you think fold/unfold and re-ordering would be a good enough solution for now? Labelled folders are doable but are just more effort.

**Comment by Gollum69** [comment]
> Thanks for bringing that up. Do you think fold/unfold and re-ordering would be a good enough solution for now? Labelled folders are doable but are just more effort.

I would believe the label system would fix this issue entirely but yeah just minimising the percentages listed for each boss would also save alot of space and allow for navigating alot easier, on top of moving bosses around so you could group them all up individually would be a fine solution too

**Comment by rugg0064** [comment]
Awaiting pull into plugin hub
https://github.com/runelite/plugin-hub/pull/4306

**Comment by Gollum69** [comment]
excellent work thank u
