### ISSUE TITLE
Bug: Doesn't work on KQ

### ISSUE THREAD

**Issue by Nick2bad4u** [rugg0064/boss-health-indicators#3]
Example: https://gyazo.com/d61e39fabb066e72c0c2a8e0a0bb8f2f

**Comment by rugg0064** [comment]
Hi, the plugin is only programmed to show incidators on bosses that have health bars like Galvek and other bosses.

![image](https://user-images.githubusercontent.com/35048262/236917218-272bb153-45ff-4d2c-8d5d-ebe842bbe029.png)

I don't have plans to add bars for older bosses without boss health bars, but maybe it's something I could do.

**Comment by Nick2bad4u** [comment]
ahh okay.

Must be a plugin im using then:

https://gyazo.com/13dbc11b08d8b81872014135678a2dcf
