### ISSUE TITLE
Trigger notification when percentage value has passed

### ISSUE THREAD

**Issue by Gollum69** [rugg0064/boss-health-indicators#5]
An idea I have thought of is to print a chat message, or perhaps other types of notifications if desired, once your user defined percentage value has been surpassed on the boss. This would make it more visible that a percentage has been passed since sometimes it'll be a few hp before the line and you're not sure if it has just passed onto the next phase or not

**Comment by rugg0064** [comment]
I'll try to find time to implement this and see how it feels, if see if it clutters any UI or anything. A beep or flash might be really useful.

**Comment by Winter** [comment]
Would definitely be a useful feature. If you're concerned about cluttering the UI you can add a tickbox next to a health percentage for the notify, clean and simple solution.

**Comment by rugg0064** [comment]
Will work on this.

**Comment by Gollum69** [comment]
> Will work on this.

wonderful to hear man i look forward to seeing it implemented

**Comment by rugg0064** [comment]
Completed, will need some sprucing up in #7, but functional right now.

**Comment by Gollum69** [comment]
honestly the way it looks right now doesn't exactly scream ugly to me. it looks functional the icon clearly suggests its a notification. if you are planning to make it look a different way then by all means
