### ISSUE TITLE
[Suggestion] Add "Hide on toolbar" option

### ISSUE THREAD

**Issue by ZeiZeiii** [rugg0064/boss-health-indicators#6]

**Comment by rugg0064** [comment]
Could you elaborate on what this means?

**Comment by Winter** [comment]
> Could you elaborate on what this means?

He's referring to the button for opening Boss Health Indicators. 
Adding a config option to toggle it when it's not needed, as one shouldn't need to go into it very often.

**Comment by rugg0064** [comment]
Will work on this.

**Comment by rugg0064** [comment]
Added in most recent commit
